const PlayerActionTypes = {
  SET_IS_PLAYING: 'SET_IS_PLAYING',
  SET_PLAYER_ITEM: 'SET_PLAYER_ITEM',
  SET_CAN_DOWNLOAD: 'SET_CAN_DOWNLOAD',
  SET_START_DOWNLOADING: 'SET_START_DOWNLOADING'
}

export default PlayerActionTypes