const HomeActionTypes = {
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  TOGGLE_CAN_SCROLL_TO_TOP: 'TOGGLE_CAN_SCROLL_TO_TOP',
  TOGGLE_SCROLL_TO_TOP: 'TOGGLE_SCROLL_TO_TOP'
}

export default HomeActionTypes